CREATE TABLE ASSIST (
	C_ID INT NOT NULL,
    E_ID INT NOT NULL,
    PRIMARY KEY (C_ID, E_ID),
    FOREIGN KEY (C_ID) REFERENCES CUSTOMER(Customer_ID),
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(Employee_ID)
);