CREATE TABLE PROCESS (
	E_ID INT NOT NULL,
    O_ID INT NOT NULL,
    PRIMARY KEY (E_ID, O_ID),
    FOREIGN KEY (E_ID) REFERENCES EMPLOYEE(Employee_ID),
    FOREIGN KEY (O_ID) REFERENCES ORDERS(Order_ID)
);